-- Crear la tabla FUNKOS
CREATE TABLE IF NOT EXISTS FUNKOS(
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    cod UUID NOT NULL DEFAULT RANDOM_UUID(),
    myid BIGINT NOT NULL,
    nombre VARCHAR(255) NOT NULL,
    modelo VARCHAR(20) CHECK(modelo IN ('MARVEL','DISNEY','ANIME','OTROS')),
    precio DOUBLE NOT NULL,
    fecha_lanzamiento DATE NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
